
apiVersion: v1
kind: Pod
metadata:
  name: test-prometheus
  #namespace: kube-system
  annotations:
    ad.datadoghq.com/test-prometheus.check_names: '["prometheus"]'
    ad.datadoghq.com/test-prometheus.init_configs: '[{}]'
    ad.datadoghq.com/test-prometheus.instances: '[{"prometheus_url": "http://%%host%%:8000/metrics", "namespace": "test_prometheus", "metrics": [{"*":"*"}]}]'
spec:
  containers:
  - image: hfaivresaito/prometheus_counter_test:latest
    imagePullPolicy: Always
    name: test-prometheus
    ports:
    - containerPort: 8000
      name: prometheus
      protocol: TCP
